package stdgen

import "github.com/husnulhamidiah/goyoga/internal/parser"

func writeTypes(dir string, api parser.API) error {
	var w Writer
	writeHeader(&w)
	w.Line(`import yoga "github.com/husnulhamidiah/goyoga/gen"`)
	w.Line("")
	w.Line("type Config struct {")
	w.Line("ref yoga.ConfigRef")
	w.Line("constRef yoga.ConfigConstRef")
	w.Line("}")
	w.Line("")
	w.Line("func wrapConfig(ref yoga.ConfigRef) *Config {")
	w.Line("if ref == nil { return nil }")
	w.Line("return &Config{ref: ref, constRef: yoga.ConfigConstRef(ref)}")
	w.Line("}")
	w.Line("")
	w.Line("func wrapConstConfig(ref yoga.ConfigConstRef) *Config {")
	w.Line("if ref == nil { return nil }")
	w.Line("return &Config{constRef: ref}")
	w.Line("}")
	w.Line("")
	w.Line("func (c *Config) yogaRef() yoga.ConfigRef {")
	w.Line("if c == nil { return nil }")
	w.Line("return c.ref")
	w.Line("}")
	w.Line("")
	w.Line("func (c *Config) yogaConstRef() yoga.ConfigConstRef {")
	w.Line("if c == nil { return nil }")
	w.Line("if c.constRef != nil { return c.constRef }")
	w.Line("return yoga.ConfigConstRef(c.ref)")
	w.Line("}")
	w.Line("")
	w.Line("type Size = yoga.Size")
	w.Line("type Value yoga.Value")
	w.Line("")
	w.Line("var ValueAuto = Value(yoga.ValueAuto)")
	w.Line("var ValueUndefined = Value(yoga.ValueUndefined)")
	w.Line("var ValueZero = Value(yoga.ValueZero)")
	w.Line("")
	w.Line("func (v Value) Equal(other Value) bool {")
	w.Line("if v.IsUndefined() && other.IsUndefined() { return true }")
	w.Line("return yoga.Value(v) == yoga.Value(other)")
	w.Line("}")
	w.Line("")
	w.Line("func (v Value) IsAuto() bool {")
	w.Line("return v.Equal(ValueAuto)")
	w.Line("}")
	w.Line("")
	w.Line("func (v Value) IsUndefined() bool {")
	w.Line("raw := yoga.Value(v)")
	w.Line("return raw != raw")
	w.Line("}")
	w.Line("")
	w.Line("func (v Value) NotEqual(other Value) bool {")
	w.Line("return !v.Equal(other)")
	w.Line("}")
	w.Line("")
	w.Line("type Layout struct {")
	w.Line("Left float32")
	w.Line("Top float32")
	w.Line("Right float32")
	w.Line("Bottom float32")
	w.Line("Width float32")
	w.Line("Height float32")
	w.Line("Direction Direction")
	w.Line("HadOverflow bool")
	w.Line("}")
	w.Line("")
	for _, td := range api.Typedefs {
		if td.FunctionPointer == nil {
			continue
		}
		name := publicName(td.Name)
		w.Line("type %s = yoga.%s", name, name)
	}
	return writeGoFile(dir, "types_generated.go", &w)
}
